TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayAssignment arrayCompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 helloStr charPointerOperation stringExample

all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 : $@
functionPointer : $@
voidPointer : $@
arrayPointer : $@
arrayAssignment : $@
arrayCompare : $@
swapFunction : $@
sumArrayFunction : $@
sumMatrixFunction: $@
sumMatrixFunction2: $@
helloStr: $@
charPointerOperation: $@
stringExample: $@

clean :
	rm ${TARGET}
