TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 arithmetics increment literal

all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
triangle2 : $@
arithmetics : $@
increment : $@
literal : $@

clean :
	rm ${TARGET}
