TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2

all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
triangle2 : $@

clean :
	rm ${TARGET}
