TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2TenSum multiplyTable ascii star one2TenWhile one2TenDoWhile randomTwoInt staticLocalVariable functionSum returnValue
all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2TenSum : $@
multiplyTable : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoInt : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@

clean :
	rm ${TARGET}
