TARGET = absolute leafYear passFail grade grade2 posZeroNeg bigLetter one2Ten one2TenSum
all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2TenSum : $@

clean :
	rm ${TARGET}
